<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-26T22:39:51 IST" name="Default suite" finished-at="2023-07-26T22:39:51 IST" duration-ms="302">
    <groups>
      <group name="search">
        <method signature="DependsOnGroupsDemo.searchProductTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" name="searchProductTest" class="com.testng.depends.DependsOnGroupsDemo"/>
      </group> <!-- search -->
      <group name="logout">
        <method signature="DependsOnGroupsDemo.logoutTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" name="logoutTest" class="com.testng.depends.DependsOnGroupsDemo"/>
      </group> <!-- logout -->
      <group name="addToCart">
        <method signature="DependsOnGroupsDemo.addToCartTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" name="addToCartTest" class="com.testng.depends.DependsOnGroupsDemo"/>
      </group> <!-- addToCart -->
      <group name="payment">
        <method signature="DependsOnGroupsDemo.paymentTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" name="paymentTest" class="com.testng.depends.DependsOnGroupsDemo"/>
      </group> <!-- payment -->
      <group name="login">
        <method signature="DependsOnGroupsDemo.loginTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" name="loginTest" class="com.testng.depends.DependsOnGroupsDemo"/>
      </group> <!-- login -->
    </groups>
    <test started-at="2023-07-26T22:39:51 IST" name="Default test" finished-at="2023-07-26T22:39:51 IST" duration-ms="302">
      <class name="com.testng.depends.DependsOnGroupsDemo">
        <test-method signature="loginTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="loginTest" finished-at="2023-07-26T22:39:51 IST" duration-ms="29" status="FAIL">
          <exception class="java.lang.ArithmeticException">
            <message>
              <![CDATA[/ by zero]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.ArithmeticException: / by zero
at com.testng.depends.DependsOnGroupsDemo.loginTest(DependsOnGroupsDemo.java:9)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ArithmeticException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="searchProductTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="searchProductTest" finished-at="2023-07-26T22:39:51 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchProductTest -->
        <test-method signature="addToCartTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="addToCartTest" depends-on-groups="login" finished-at="2023-07-26T22:39:51 IST" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnGroupsDemo.addToCartTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnGroupsDemo.addToCartTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addToCartTest -->
        <test-method signature="generateReportTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="generateReportTest" depends-on-groups="login" finished-at="2023-07-26T22:39:51 IST" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReportTest -->
        <test-method signature="logoutTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="logoutTest" depends-on-groups="login" finished-at="2023-07-26T22:39:51 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnGroupsDemo.logoutTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnGroupsDemo.logoutTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutTest -->
        <test-method signature="paymentTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8]" started-at="2023-07-26T22:39:51 IST" name="paymentTest" depends-on-groups="login" finished-at="2023-07-26T22:39:51 IST" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method DependsOnGroupsDemo.paymentTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method DependsOnGroupsDemo.paymentTest()[pri:0, instance:com.testng.depends.DependsOnGroupsDemo@76b1e9b8] depends on not successfully finished methods in group "login"
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentTest -->
      </class> <!-- com.testng.depends.DependsOnGroupsDemo -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
